import type { Equipo, HojaDeVida, RepuestoAccesorio, Mantenimiento, DocumentoManual } from '@/shared/types'

export const INITIAL_EQUIPOS: Equipo[] = [
  {
    id: 'e1-tm35-001',
    codigo_qr: 'CAP-TM35-001',
    placa_inventario: 'ACT-BIO-142526',
    numero_serie: 'SN-TM35-2026-8849',
    marca: 'Medtronic',
    modelo: 'Capnostream 35',
    nombre_equipo: 'Capnógrafo Portátil de Muestreo Secundario (Sidestream)',
    tecnologia: 'Sidestream',
    clasificacion_riesgo: 'Clase IIb',
    clasificacion_biomedica: 'Soporte de Vida',
    ubicacion_servicio: 'UCI Adultos - Unidad Coronaria',
    ubicacion_especifica: 'Cama 04 (Atril rodante)',
    estado_operativo: 'Operativo',
    horas_bomba_acumuladas: 142.5,
    fecha_adquisicion: '2025-08-15',
    fecha_instalacion: '2025-08-20',
    garantia_vencimiento: '2027-08-20',
    created_at: '2025-08-20T10:00:00Z',
  },
  {
    id: 'e2-tm35-002',
    codigo_qr: 'CAP-TM35-002',
    placa_inventario: 'ACT-BIO-144048',
    numero_serie: 'SN-TM35-2026-8912',
    marca: 'Medtronic',
    modelo: 'Capnostream 35',
    nombre_equipo: 'Capnógrafo Portátil de Muestreo Secundario',
    tecnologia: 'Sidestream',
    clasificacion_riesgo: 'Clase IIb',
    clasificacion_biomedica: 'Soporte de Vida',
    ubicacion_servicio: 'Quirófano Quirúrgico 3',
    ubicacion_especifica: 'Torre de Anestesia B',
    estado_operativo: 'Calibración Pendiente',
    horas_bomba_acumuladas: 388.0,
    fecha_adquisicion: '2025-03-10',
    fecha_instalacion: '2025-03-15',
    garantia_vencimiento: '2027-03-15',
    created_at: '2025-03-15T14:30:00Z',
  },
  {
    id: 'e3-tm35-003',
    codigo_qr: 'CAP-TM35-003',
    placa_inventario: 'ACT-BIO-144647',
    numero_serie: 'SN-TM35-2026-9041',
    marca: 'Medtronic',
    modelo: 'Capnostream 35',
    nombre_equipo: 'Capnógrafo de Transporte Urgencias',
    tecnologia: 'Sidestream',
    clasificacion_riesgo: 'Clase IIb',
    clasificacion_biomedica: 'Monitoreo',
    ubicacion_servicio: 'Urgencias - Reanimación',
    ubicacion_especifica: 'Carro de Paro 1',
    estado_operativo: 'Operativo',
    horas_bomba_acumuladas: 96.2,
    fecha_adquisicion: '2025-11-01',
    fecha_instalacion: '2025-11-05',
    garantia_vencimiento: '2027-11-05',
    created_at: '2025-11-05T09:00:00Z',
  }
]

export const INITIAL_HOJAS_VIDA: Record<string, HojaDeVida> = {
  'e1-tm35-001': {
    id: 'hv-001',
    id_equipo: 'e1-tm35-001',
    registro_invima: 'INVIMA 2018EBC-0018492',
    voltaje_operacion: '100 - 240 VAC',
    frecuencia_red: '50 / 60 Hz',
    potencia_consumo: '45 VA',
    tipo_alimentacion: 'Red eléctrica 110V + Batería Li-ion interna (Smart Battery)',
    flujo_nominal_aspiracion: 50.0,
    tolerancia_flujo_mlmin: 7.5,
    rango_medicion_etco2: '0 a 99 mmHg (0 a 13.2 kPa)',
    frecuencia_mantenimiento_dias: 180,
    frecuencia_calibracion_dias: 365,
    fecha_ultimo_mantenimiento: '2026-08-15',
    fecha_proximo_mantenimiento: '2027-02-15',
    fecha_ultima_calibracion: '2026-05-10',
    fecha_proxima_calibracion: '2027-05-10',
    manual_servicio_referencia: 'Medtronic Capnostream 35 Portable Bedside Monitor Service Manual',
    norma_seguridad_electrica: 'IEC 62353 / IEC 60601-1',
    observaciones_tecnicas: 'Equipo con celda infrarroja NDIR calibrada con gas patrón al 5.0% CO2. Flujo verificado en 49.8 mL/min (tolerancia 50 ± 7.5 mL/min conforme).'
  },
  'e2-tm35-002': {
    id: 'hv-002',
    id_equipo: 'e2-tm35-002',
    registro_invima: 'INVIMA 2018EBC-0018492',
    voltaje_operacion: '100 - 240 VAC',
    frecuencia_red: '50 / 60 Hz',
    potencia_consumo: '45 VA',
    tipo_alimentacion: 'Red eléctrica + Batería Li-ion',
    flujo_nominal_aspiracion: 50.0,
    tolerancia_flujo_mlmin: 7.5,
    rango_medicion_etco2: '0 a 99 mmHg (0 a 13.2 kPa)',
    frecuencia_mantenimiento_dias: 180,
    frecuencia_calibracion_dias: 365,
    fecha_ultimo_mantenimiento: '2026-04-01',
    fecha_proximo_mantenimiento: '2026-10-01',
    fecha_ultima_calibracion: '2025-09-20',
    fecha_proxima_calibracion: '2026-09-20',
    manual_servicio_referencia: 'Medtronic Capnostream 35 Service Manual',
    norma_seguridad_electrica: 'IEC 62353',
    observaciones_tecnicas: 'Alerta de calibración anual vencida según Resolución 3100. Requiere verificación de cero y span con gas patrón de calibración.'
  },
  'e3-tm35-003': {
    id: 'hv-003',
    id_equipo: 'e3-tm35-003',
    registro_invima: 'INVIMA 2018EBC-0018492',
    voltaje_operacion: '100 - 240 VAC',
    frecuencia_red: '50 / 60 Hz',
    potencia_consumo: '45 VA',
    tipo_alimentacion: 'Red eléctrica + Batería Li-ion',
    flujo_nominal_aspiracion: 50.0,
    tolerancia_flujo_mlmin: 7.5,
    rango_medicion_etco2: '0 a 99 mmHg (0 a 13.2 kPa)',
    frecuencia_mantenimiento_dias: 180,
    frecuencia_calibracion_dias: 365,
    fecha_ultimo_mantenimiento: '2026-07-20',
    fecha_proximo_mantenimiento: '2027-01-20',
    fecha_ultima_calibracion: '2026-07-20',
    fecha_proxima_calibracion: '2027-07-20',
    manual_servicio_referencia: 'Medtronic Capnostream 35 Service Manual',
    norma_seguridad_electrica: 'IEC 62353',
    observaciones_tecnicas: 'Unidad de transporte de urgencias. Estado físico y neumático óptimo.'
  }
}

export const INITIAL_REPUESTOS: RepuestoAccesorio[] = [
  {
    id: 'r1',
    codigo_referencia: 'LPA3948',
    nombre: 'Línea de muestreo Microstream FilterLine (Adulto/Pediátrico)',
    categoria: 'Consumible',
    descripcion: 'Línea con trampa de humedad y filtro bacteriano para paciente intubado/no intubado',
    numero_lote: 'LOT-2026-A1',
    registro_invima: 'INVIMA 2018DM-0018492',
    stock_actual: 10,
    stock_minimo: 3,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 45000,
  },
  {
    id: 'r2',
    codigo_referencia: 'LNI9384',
    nombre: 'Línea de muestreo Microstream FilterLine (Neonatal/Infantil)',
    categoria: 'Consumible',
    descripcion: 'Línea pediátrica neonatal de bajo espacio muerto muerto para monitoreo continuo',
    numero_lote: 'LOT-2026-N2',
    registro_invima: 'INVIMA 2018DM-0018492',
    stock_actual: 10,
    stock_minimo: 3,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 52000,
  },
  {
    id: 'r3',
    codigo_referencia: 'LN0X8877',
    nombre: 'Línea de muestreo FilterLine con línea de O2 combinada',
    categoria: 'Consumible',
    descripcion: 'Línea dual para suministro de oxígeno complementario y aspiración de EtCO2',
    numero_lote: 'LOT-2026-O3',
    registro_invima: 'INVIMA 2018DM-0018492',
    stock_actual: 5,
    stock_minimo: 2,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 68000,
  },
  {
    id: 'r4',
    codigo_referencia: 'LNCAP48',
    nombre: 'Línea de muestreo Smart CapnoLine Hemo',
    categoria: 'Consumible',
    descripcion: 'Línea de alta durabilidad resistente a humedad y secreciones bronquiales',
    numero_lote: 'LOT-2026-H4',
    registro_invima: 'INVIMA 2018DM-0018492',
    stock_actual: 5,
    stock_minimo: 2,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 75000,
  },
  {
    id: 'r5',
    codigo_referencia: 'FIL7780',
    nombre: 'Filtro hidrófobo o trampa de humedad de repuesto',
    categoria: 'Consumible',
    descripcion: 'Filtro de protección neumática para celda de detección óptica NDIR',
    numero_lote: 'LOT-2026-F5',
    registro_invima: 'INVIMA 2018DM-0018492',
    stock_actual: 3,
    stock_minimo: 2,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 38000,
  },
  {
    id: 'r6',
    codigo_referencia: 'PAPTYER993',
    nombre: 'Papel térmico para impresora integrada',
    categoria: 'Consumible',
    descripcion: 'Rollo de papel termosensible 58mm para registro de tendencias de capnograma',
    numero_lote: 'LOT-2026-P6',
    stock_actual: 6,
    stock_minimo: 2,
    unidad_medida: 'Rollo',
    ubicacion_almacen: 'Almacén Biomédica - Gaveta Insumos Capnografía',
    estado: 'Disponible',
    precio_unitario_estimado: 12000,
  },
  {
    id: 'r7',
    codigo_referencia: 'SPO2-ADU',
    nombre: 'Sensor de SpO2 reutilizable Adulto (Dedo)',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Sensor óptico de pulsoximetría tecnología Nellcor compatible',
    numero_lote: 'LOT-2025-S1',
    stock_actual: 2,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Vitrina de Accesorios Especiales',
    estado: 'Disponible',
    precio_unitario_estimado: 350000,
  },
  {
    id: 'r8',
    codigo_referencia: 'SPO2-NEO',
    nombre: 'Sensor de SpO2 suave de silicona (Neonatal / Pediátrico)',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Sensor tipo envoltura suave para pacientes neonatales y pediátricos',
    numero_lote: 'LOT-2025-S2',
    stock_actual: 2,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Vitrina de Accesorios Especiales',
    estado: 'Disponible',
    precio_unitario_estimado: 380000,
  },
  {
    id: 'r9',
    codigo_referencia: 'CBL-SPO2',
    nombre: 'Cable troncal de SpO2 (Interface Cable)',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Cable de extensión y conexión al conector frontal del monitor Capnostream 35',
    numero_lote: 'LOT-2025-C1',
    stock_actual: 2,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Vitrina de Accesorios Especiales',
    estado: 'Disponible',
    precio_unitario_estimado: 290000,
  },
  {
    id: 'r10',
    codigo_referencia: 'BAT-TM35',
    nombre: 'Batería externa de repuesto (Smart Battery Pack)',
    categoria: 'Repuesto Electroneumático',
    descripcion: 'Pack inteligente de Ion-Litio con indicador de nivel de carga integrado',
    numero_lote: 'LOT-2025-B1',
    stock_actual: 1,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Cajón de Baterías Biomédica',
    estado: 'Stock Bajo',
    precio_unitario_estimado: 850000,
  },
  {
    id: 'r11',
    codigo_referencia: 'ATR-ROD',
    nombre: 'Base rodante o atril con canastilla',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Soporte móvil hospitalario con ruedas antiestáticas, freno y canastilla',
    stock_actual: 3,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Taller de Equipos de Soporte',
    estado: 'Disponible',
    precio_unitario_estimado: 420000,
  },
  {
    id: 'r12',
    codigo_referencia: 'MAL-TRA',
    nombre: 'Maletín de transporte portátil de lona impermeable',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Bolso acolchado con divisiones para monitor, sensor, cargador y consumibles',
    stock_actual: 1,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Vitrina de Accesorios Especiales',
    estado: 'Stock Bajo',
    precio_unitario_estimado: 180000,
  },
  {
    id: 'r13',
    codigo_referencia: 'PRT-SIL',
    nombre: 'Protector de pantalla de silicona o carcasa anti-golpes',
    categoria: 'Accesorio Reutilizable',
    descripcion: 'Funda de amortiguación perimetral para protección de carcasa plástica',
    stock_actual: 1,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Vitrina de Accesorios Especiales',
    estado: 'Stock Bajo',
    precio_unitario_estimado: 125000,
  },
  {
    id: 'r14',
    codigo_referencia: 'MOD-FLU449',
    nombre: 'Módulo de sensor de flujo o muestreo neumático de repuesto',
    categoria: 'Repuesto Electroneumático',
    descripcion: 'Bloque de microbomba de succión Sidestream 50 mL/min con electroválvula de purga',
    numero_lote: 'LOT-2025-M1',
    stock_actual: 1,
    stock_minimo: 1,
    unidad_medida: 'Unidad',
    ubicacion_almacen: 'Cajón de Componentes Críticos Neumáticos',
    estado: 'Stock Bajo',
    precio_unitario_estimado: 1450000,
  }
]

export const INITIAL_MANTENIMIENTOS: Mantenimiento[] = []

export const INITIAL_MANUALES: DocumentoManual[] = [
  {
    id: 'man-001',
    modelo_equipo: 'Capnostream 35',
    titulo: 'Manual de Usuario Oficial Medtronic Capnostream 35',
    tipo_documento: 'Manual de Usuario',
    nombre_archivo: 'MANUAL DE USUARIO TM 35.pdf',
    storage_path: 'Docs/MANUAL DE USUARIO TM 35.pdf',
    tamano_bytes: 6933940,
    formato: 'application/pdf',
    total_paginas: 156,
    estado_indexacion: 'Indexado',
    created_at: '2026-08-31T12:00:00Z',
  },
  {
    id: 'man-002',
    modelo_equipo: 'Capnostream 35',
    titulo: 'Guía de Mantenimiento y Calibración Metrológica IEC 62353',
    tipo_documento: 'Protocolo de Calibración',
    nombre_archivo: 'HOJA DE VIDA EQUIPO TM35.xlsx - Hoja1.pdf',
    storage_path: 'Docs/HOJA DE VIDA EQUIPO TM35.xlsx - Hoja1.pdf',
    tamano_bytes: 165185,
    formato: 'application/pdf',
    total_paginas: 2,
    estado_indexacion: 'Indexado',
    created_at: '2026-08-31T12:00:00Z',
  }
]
